name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

 
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.c3dezign.com
        username: admin@hasnatech.com
        password: nP^OcO{q4p]U
        local-dir: ./dist/website/browser/
        remote-dir: /public_html/hasnatechcom/

# ftp.c3dezign.com
# admin@hasnatech.com
# nP^OcO{q4p]U